theme: jekyll-theme-cayman
title: Welcome to William's Portfolio
description: Feel free to look around and drop me an email if anything im doing sounds interesting to you!
header_pages:
	- index.md
    - about.md
